import json

tasks_data = {
    "Grill (2 Cooks)": [
        {"task": "Marking grill grates flipped, scraped bare, bricks used, completely to silver (use water & oil)"},
        {"task": "Wood grill scrubbed down, bricks used, to silver (use water & oil)"},
        {"task": "Grill backwall scrubbed free of debris and soot"},
        {"task": "Grease traps emptied, wiped down"},
        {"task": "Below wood grill wiped down"},
        {"task": "Ash swept from under wood grill, floor swept & mopped"},
        {"task": "Prep table wiped, cutting boards flipped or cleaned"},
        {"task": "Wood/coal supply replenished for next day"},
        {"task": "Cooler drawers wiped inside and out"},
        {"task": "Protein pans changed out, dates checked, relabeled"},
        {"task": "Trash cans emptied and scrubbed"},
        {"task": "Wipe KDS screens and bump bars"},
        {"task": "Complete Restock Chart (Pans, tongs, bottles, etc.)", "details": "1x Chx grate, 1x Fish grate, 1x Meat grate, 1x Yellow tongs, 1x Blue tongs, 1x Red tongs, 1x Black tongs, 2x Green tongs, 1x Bbq brush, 2x Red scoop, 1x 1/9 pans, 1x Oil spray bottle, 1x Butter bottle, 1x Yellow cutting board, 1x Red scoop, 1x 1/6 pan, 1x Green scoop, 1x White scoop, 2x Grey scoop, 1x 5oz ladle, 3x 2Qt Cambro & Lid, 1x Tan cup, 3x Small spatula"},
        {"task": "Hoods", "day_of_week": "Monday"},
        {"task": "Detail oven and cubby", "day_of_week": "Tuesday"},
        {"task": "Back wall, detail char grill", "day_of_week": "Wednesday"},
        {"task": "Detail saute grill", "day_of_week": "Thursday"},
        {"task": "Detail DRAINS", "day_of_week": "Sunday"},
        {"task": "Equipment line", "day_of_week": "Monday"},
        {"task": "Service line", "day_of_week": "Tuesday"},
        {"task": "Equipment Line", "day_of_week": "Wednesday"},
        {"task": "Service Line", "day_of_week": "Thursday"},
        {"task": "Equipment Line", "day_of_week": "Friday"},
        {"task": "Service Line", "day_of_week": "Saturday"}
    ],
    "Grill (3 Cooks)": [
        {"task": "Wood grill scrubbed down, bricks used, to silver (use water & oil)"},
        {"task": "Wood grill backwall scrubbed free of debris and soot"},
        {"task": "Grease traps emptied, wiped down"},
        {"task": "Below wood grill wiped down"},
        {"task": "Ash swept from under wood grill, floor swept & mopped"},
        {"task": "Wood/coal supply replenished for next day"},
        {"task": "Cooler drawers wiped inside and out"},
        {"task": "Protein pans changed out, dates checked, relabeled"},
        {"task": "Trash cans emptied and scrubbed"},
        {"task": "Wipe KDS screens and bump bars"},
        {"task": "Complete Restock Chart (Pans, tongs, bottles, etc.)", "details": "1x Bbq brush, 2x Red scoop, 1x 1/9 pans, 1x Oil spray bottle, 1x Butter bottle, 1x Yellow cutting board, 1x Red scoop, 1x 1/6 pan"},
        {"task": "Hoods", "day_of_week": "Monday"},
        {"task": "Detail oven and cubby", "day_of_week": "Tuesday"},
        {"task": "Back wall, detail char grill", "day_of_week": "Wednesday"},
        {"task": "Detail saute grill", "day_of_week": "Thursday"},
        {"task": "Detail DRAINS", "day_of_week": "Sunday"},
        {"task": "Equipment line", "day_of_week": "Monday"},
        {"task": "Service line", "day_of_week": "Tuesday"},
        {"task": "Equipment Line", "day_of_week": "Wednesday"},
        {"task": "Service Line", "day_of_week": "Thursday"},
        {"task": "Equipment Line", "day_of_week": "Friday"},
        {"task": "Service Line", "day_of_week": "Saturday"}
    ],
    "Saute (2 Cooks)": [
        {"task": "ALL pans in sauté cooler flipped, relabeled, lids put on, and fully stocked. Ice bags on proteins, filet skewers in walk-in"},
        {"task": "Wipe inside of sauté cooler and drawers"},
        {"task": "Oven cleaned from top to bottom"},
        {"task": "Back wall wiped, grease traps checked"},
        {"task": "Clean shelf above"},
        {"task": "Clean, fill & label shakers, flip & fill seasoning pans as needed"},
        {"task": "Clean all aspects of clamshell grill, clean troughs, wipe down Teflon gently"},
        {"task": "Clean marking grill. Scrap off buildup, replace pans, wipe out the catch on the bottom, run marking weights through dish, replace meat seasoning grate"},
        {"task": "Clean bbq/mushroom hot well"},
        {"task": "Clean Saute floor"},
        {"task": "Wipe down KDS, replace saran wrap on bump bar"},
        {"task": "Clean 3 comp sink"},
        {"task": "Complete Restock Chart (Pans, tongs, bottles, etc.)", "details": "1x Chx grate, 1x Fish grate, 1x Meat grate, 2x Yellow tongs, 2x Blue tongs, 1x Red tongs, 1x Black tongs, 1x Green tongs, 1x Bbq brush, 2x Red scoop, 2x 1/9 pans, 1x Oil spray bottle, 1x Butter bottle, 1x Yellow cutting board, 1x Red scoop, 1x 1/6 pan, 2x Green scoop, 1x White scoop, 2x Grey scoop, 1x 5oz ladle, 3x 2Qt Cambro & Lid, 1x Tan cup, 3x Small spatula"},
        {"task": "Hoods", "day_of_week": "Monday"},
        {"task": "Detail oven and cubby", "day_of_week": "Tuesday"},
        {"task": "Back wall, detail char grill", "day_of_week": "Wednesday"},
        {"task": "Detail saute grill", "day_of_week": "Thursday"},
        {"task": "Detail DRAINS", "day_of_week": "Sunday"},
        {"task": "Equipment line", "day_of_week": "Monday"},
        {"task": "Service line", "day_of_week": "Tuesday"},
        {"task": "Equipment Line", "day_of_week": "Wednesday"},
        {"task": "Service Line", "day_of_week": "Thursday"},
        {"task": "Equipment Line", "day_of_week": "Friday"},
        {"task": "Service Line", "day_of_week": "Saturday"}
    ],
    "Saute (3 Cooks)": [
        {"task": "ALL pans in sauté cooler flipped, relabeled, lids put on, and fully stocked. Ice bags on proteins, filet skewers in walk-in"},
        {"task": "Wipe inside of sauté cooler and drawers"},
        {"task": "Oven cleaned from top to bottom"},
        {"task": "Back wall wiped, grease traps checked"},
        {"task": "Clean shelf above"},
        {"task": "Clean, fill & label shakers, flip & fill seasoning pans as needed"},
        {"task": "Clean bbq/mushroom hot well"},
        {"task": "Clean Saute floor"},
        {"task": "Wipe down KDS, replace saran wrap on bump bar"},
        {"task": "Clean 3 comp sink"},
        {"task": "Complete Restock Chart (Pans, tongs, bottles, etc.)", "details": "1x Chx grate, 1x Fish grate, 1x Meat grate, 2x Yellow tongs, 2x Blue tongs, 1x Red tongs, 1x Black tongs, 1x Green tongs, 1x Bbq brush, 2x Red scoop, 2x 1/9 pans, 1x Oil spray bottle, 1x Butter bottle, 1x Yellow cutting board, 1x Red scoop, 1x 1/6 pan, 2x Green scoop, 1x White scoop, 2x Grey scoop, 1x 5oz ladle, 3x 2Qt Cambro & Lid, 1x Tan cup, 3x Small spatula"},
        {"task": "Hoods", "day_of_week": "Monday"},
        {"task": "Detail oven and cubby", "day_of_week": "Tuesday"},
        {"task": "Back wall, detail char grill", "day_of_week": "Wednesday"},
        {"task": "Detail saute grill", "day_of_week": "Thursday"},
        {"task": "Detail DRAINS", "day_of_week": "Sunday"},
        {"task": "Equipment line", "day_of_week": "Monday"},
        {"task": "Service line", "day_of_week": "Tuesday"},
        {"task": "Equipment Line", "day_of_week": "Wednesday"},
        {"task": "Service Line", "day_of_week": "Thursday"},
        {"task": "Equipment Line", "day_of_week": "Friday"},
        {"task": "Service Line", "day_of_week": "Saturday"}
    ],
    "Make-up": [
        {"task": "Clean all aspects of clamshell grill, clean troughs, wipe down Teflon gently"},
        {"task": "Clean marking grill. Scrap off buildup, replace pans, wipe out the catch on the bottom, run marking weights through dish, replace meat seasoning grate"},
        {"task": "Clean shelf above"},
        {"task": "Clean, fill & label shakers, flip & fill seasoning pans as needed"},
        {"task": "Wipe inside of sauté cooler and drawers"},
        {"task": "Clean Make-up floor"},
        {"task": "Wipe down KDS, replace saran wrap on bump bar"},
        {"task": "Complete Restock Chart (Pans, tongs, bottles, etc.)", "details": "1x Chx grate, 1x Fish grate, 1x Meat grate, 1x Yellow tongs, 1x Blue tongs, 1x Red tongs, 1x Black tongs, 2x Green tongs, 1x Green scoop, 1x White scoop, 2x Grey scoop, 1x 5oz ladle, 3x 2Qt Cambro & Lid, 1x Tan cup, 3x Small spatula"},
        {"task": "Hoods", "day_of_week": "Monday"},
        {"task": "Detail oven and cubby", "day_of_week": "Tuesday"},
        {"task": "Back wall, detail char grill", "day_of_week": "Wednesday"},
        {"task": "Detail saute grill", "day_of_week": "Thursday"},
        {"task": "Detail DRAINS", "day_of_week": "Sunday"},
        {"task": "Equipment line", "day_of_week": "Monday"},
        {"task": "Service line", "day_of_week": "Tuesday"},
        {"task": "Equipment Line", "day_of_week": "Wednesday"},
        {"task": "Service Line", "day_of_week": "Thursday"},
        {"task": "Equipment Line", "day_of_week": "Friday"},
        {"task": "Service Line", "day_of_week": "Saturday"}
    ],
    "Fry": [
        {"task": "Turn off fryers and filter oil"},
        {"task": "Scrub the vats and clean the sides/backsplash of fryers"},
        {"task": "Empty grease traps and clean them"},
        {"task": "Sweep and mop behind/under the fryers"},
        {"task": "Clean and restock fry freezer, label all items"},
        {"task": "Wipe down microwave and fry pass area"},
        {"task": "Take all trash out and replace liners"},
        {"task": "Clean and restock breading station"},
        {"task": "Wipe down KDS screens"},
        {"task": "Complete Restock Chart (Pans, tongs, baskets, etc.)", "details": "6x Fry baskets, 2x Skimmers, 2x Tongs, 1x Spider, 3x 1/3 pans, 2x 1/6 pans"},
        {"task": "Detail ice cream freezer and bowl chiller", "day_of_week": "Monday"},
        {"task": "Take down all uptop items and clean stainless", "day_of_week": "Tuesday"},
        {"task": "Detail Fry Freezer", "day_of_week": "Wednesday"},
        {"task": "Detail salad reach in", "day_of_week": "Thursday"},
        {"task": "Detail DRAINS", "day_of_week": "Sunday"},
        {"task": "Equipment line", "day_of_week": "Monday"},
        {"task": "Service line", "day_of_week": "Tuesday"},
        {"task": "Equipment Line", "day_of_week": "Wednesday"},
        {"task": "Service Line", "day_of_week": "Thursday"},
        {"task": "Equipment Line", "day_of_week": "Friday"},
        {"task": "Service Line", "day_of_week": "Saturday"}
    ],
    "Salad (2 Cooks)": [
        {"task": "Flip, re-label, and fill ALL pans, flip lettuce bins, label, and return to walk-in"},
        {"task": "Wipe down all shelves and top of station, restock all togo supplies"},
        {"task": "Stock and label rusks"},
        {"task": "Wipe inside, outside, handles, drawers and doors on cooler. Make sure no water is collecting."},
        {"task": "Spray down cutting board in the mop sink."},
        {"task": "Clean dip well. Replace the pans"},
        {"task": "Ice-cream freezer cleaned, replace lid on ice-cream"},
        {"task": "Check dessert labels, combine/wash/refill melba"},
        {"task": "Microwave and handle wiped down."},
        {"task": "Wipe KDS screen, cover bump bar with saran wrap."},
        {"task": "Clean soup well, replace pans & lids & stack."},
        {"task": "Sweep the line."},
        {"task": "Clean salad floor."},
        {"task": "Large bowls, small bowls, and plates restocked in bowl chiller."},
        {"task": "Bowl chiller wiped out"},
        {"task": "Turn off fryers and filter oil"},
        {"task": "Scrub the vats and clean the sides/backsplash of fryers"},
        {"task": "Empty grease traps and clean them"},
        {"task": "Sweep and mop behind/under the fryers"},
        {"task": "Clean and restock fry freezer, label all items"},
        {"task": "Clean and restock breading station"},
        {"task": "All personal belongings taken care of."},
        {"task": "Trashes run"},
        {"task": "Complete Restock Chart (Ladles, scoops, pans, etc.)", "details": "1x 2oz ladle, 3x 3oz ladle, 1x 6oz ladle, 2x 5oz ladle, 8x 1.5oz ladle, 5x 1oz ladle, 2x White scoop, 1x Tan cup, 2x Green scoop, 2x Brown lettuce scoop, 2x Blue scoop, 4x Red scoop, 1x 60 scoop, 3x 100 scoop, 4x TBSP, 1x 1/2 TBSP, 2x Stainless bowl, 2x Metal 1/9 pans, 1x 1/2 cup"},
        {"task": "Detail ice cream freezer and bowl chiller", "day_of_week": "Monday"},
        {"task": "Take down all uptop items and clean stainless", "day_of_week": "Tuesday"},
        {"task": "Detail Fry Freezer", "day_of_week": "Wednesday"},
        {"task": "Detail salad reach in", "day_of_week": "Thursday"},
        {"task": "Detail DRAINS", "day_of_week": "Sunday"},
        {"task": "Equipment line", "day_of_week": "Monday"},
        {"task": "Service line", "day_of_week": "Tuesday"},
        {"task": "Equipment Line", "day_of_week": "Wednesday"},
        {"task": "Service Line", "day_of_week": "Thursday"},
        {"task": "Equipment Line", "day_of_week": "Friday"},
        {"task": "Service Line", "day_of_week": "Saturday"}
    ],
    "Salad (3 Cooks)": [
        {"task": "Flip, re-label, and fill ALL pans, flip lettuce bins, label, and return to walk-in"},
        {"task": "Wipe down all shelves and top of station, restock all togo supplies."},
        {"task": "Stock and label rusks"},
        {"task": "Wipe inside, outside, handles, drawers and doors on cooler. Make sure no water is collecting."},
        {"task": "Spray down cutting board in the mop sink."},
        {"task": "Clean dip well. Replace the pans"},
        {"task": "Ice-cream freezer cleaned, replace lid on ice-cream"},
        {"task": "Check dessert labels, combine/wash/refill melba"},
        {"task": "Microwave and handle wiped down."},
        {"task": "Wipe KDS screen, cover bump bar with saran wrap."},
        {"task": "Clean soup well, replace pans & lids & stack."},
        {"task": "Sweep the line."},
        {"task": "Clean salad floor."},
        {"task": "Large bowls, small bowls, and plates restocked in bowl chiller."},
        {"task": "Bowl chiller wiped out"},
        {"task": "All personal belongings taken care of."},
        {"task": "Trashes run"},
        {"task": "Complete Restock Chart (Ladles, scoops, pans, etc.)", "details": "1x 2oz ladle, 3x 3oz ladle, 1x 6oz ladle, 2x 5oz ladle, 8x 1.5oz ladle, 5x 1oz ladle, 2x White scoop, 1x Tan cup, 2x Green scoop, 2x Brown lettuce scoop, 2x Blue scoop, 4x Red scoop, 1x 60 scoop, 3x 100 scoop, 4x TBSP, 1x 1/2 TBSP, 2x Stainless bowl, 2x Metal 1/9 pans, 1x 1/2 cup"},
        {"task": "Detail ice cream freezer and bowl chiller", "day_of_week": "Monday"},
        {"task": "Take down all uptop items and clean stainless", "day_of_week": "Tuesday"},
        {"task": "Detail Fry Freezer", "day_of_week": "Wednesday"},
        {"task": "Detail salad reach in", "day_of_week": "Thursday"},
        {"task": "Detail DRAINS", "day_of_week": "Sunday"},
        {"task": "Equipment line", "day_of_week": "Monday"},
        {"task": "Service line", "day_of_week": "Tuesday"},
        {"task": "Equipment Line", "day_of_week": "Wednesday"},
        {"task": "Service Line", "day_of_week": "Thursday"},
        {"task": "Equipment Line", "day_of_week": "Friday"},
        {"task": "Service Line", "day_of_week": "Saturday"}
    ],
    "Bloom (2 Cooks)": [
        {"task": "Clean bloom breading station, sift flour, change water/milk wash"},
        {"task": "Wipe down bloom reach-in cooler, restock petals/onions"},
        {"task": "Filter bloom fryer oil, scrub vat"},
        {"task": "Clean bloom station floor"},
        {"task": "Wipe down cutting boards and prep area"},
        {"task": "Restock sauce ramekins and large bloom plates"},
        {"task": "Empty grease traps and wipe down backsplash"},
        {"task": "Empty trashes"},
        {"task": "Sweep and mop the floor"},
        {"task": "Clean breading station components (sifter, pans)"},
        {"task": "Detail ice cream freezer and bowl chiller", "day_of_week": "Monday"},
        {"task": "Take down all uptop items and clean stainless", "day_of_week": "Tuesday"},
        {"task": "Detail Fry Freezer", "day_of_week": "Wednesday"},
        {"task": "Detail salad reach in", "day_of_week": "Thursday"},
        {"task": "Detail DRAINS", "day_of_week": "Sunday"},
        {"task": "Equipment line", "day_of_week": "Monday"},
        {"task": "Service line", "day_of_week": "Tuesday"},
        {"task": "Equipment Line", "day_of_week": "Wednesday"},
        {"task": "Service Line", "day_of_week": "Thursday"},
        {"task": "Equipment Line", "day_of_week": "Friday"},
        {"task": "Service Line", "day_of_week": "Saturday"}
    ],
    "Bloom (3 Cooks)": [
        {"task": "Clean bloom breading station, sift flour, change water/milk wash"},
        {"task": "Wipe down bloom reach-in cooler, restock petals/onions"},
        {"task": "Filter bloom fryer oil, scrub vat"},
        {"task": "Clean bloom station floor"},
        {"task": "Wipe down cutting boards and prep area"},
        {"task": "Restock sauce ramekins and large bloom plates"},
        {"task": "Empty grease traps and wipe down backsplash"},
        {"task": "Empty trashes"},
        {"task": "Detail ice cream freezer and bowl chiller", "day_of_week": "Monday"},
        {"task": "Take down all uptop items and clean stainless", "day_of_week": "Tuesday"},
        {"task": "Detail Fry Freezer", "day_of_week": "Wednesday"},
        {"task": "Detail salad reach in", "day_of_week": "Thursday"},
        {"task": "Detail DRAINS", "day_of_week": "Sunday"},
        {"task": "Equipment line", "day_of_week": "Monday"},
        {"task": "Service line", "day_of_week": "Tuesday"},
        {"task": "Equipment Line", "day_of_week": "Wednesday"},
        {"task": "Service Line", "day_of_week": "Thursday"},
        {"task": "Equipment Line", "day_of_week": "Friday"},
        {"task": "Service Line", "day_of_week": "Saturday"}
    ]
}

with open('default_tasks.json', 'w') as f:
    json.dump(tasks_data, f, indent=4)
print("Created default_tasks.json")
