-- Run this SQL in your Supabase SQL Editor to create the necessary tables

CREATE TABLE IF NOT EXISTS closing_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TEXT NOT NULL,
    employee_name TEXT NOT NULL,
    station TEXT NOT NULL,
    photo_data TEXT, -- Base64 encoded string
    image_url TEXT,
    status TEXT DEFAULT 'APPROVED'
);

CREATE TABLE IF NOT EXISTS shift_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_date TEXT NOT NULL,
    shift_type TEXT,
    total_sales REAL,
    total_labor_cost REAL,
    labor_percentage REAL,
    avg_ticket_time INTEGER,
    waste_cost REAL
);
