-- Run this SQL in your Supabase SQL Editor to create the necessary tables

CREATE TABLE IF NOT EXISTS closing_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TEXT NOT NULL,
    employee_name TEXT NOT NULL,
    station TEXT NOT NULL,
    photo_data TEXT, -- Base64 encoded string
    image_url TEXT,
    status TEXT DEFAULT 'APPROVED'
);

CREATE TABLE IF NOT EXISTS shift_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_date TEXT NOT NULL,
    shift_type TEXT,
    total_sales REAL,
    total_labor_cost REAL,
    labor_percentage REAL,
    avg_ticket_time INTEGER,
    waste_cost REAL
);

-- Run this to create the station tasks table
CREATE TABLE IF NOT EXISTS station_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station TEXT NOT NULL,
    task TEXT NOT NULL
);

-- Insert default tasks
INSERT INTO station_tasks (station, task) VALUES
    ('Fry Station', 'Oil filtered and vats scrubbed'),
    ('Fry Station', 'Backsplash degreased (zero carbon buildup)'),
    ('Fry Station', 'Floor drains cleared of debris'),
    ('Grill Station', 'Grates scraped and bricked to silver'),
    ('Grill Station', 'Drip pans emptied and sanitized'),
    ('Grill Station', 'Under-grill sweeps completed'),
    ('Prep / Walk-in', 'All open containers wrapped, dated, and labeled'),
    ('Prep / Walk-in', 'Floors swept and mopped'),
    ('Prep / Walk-in', 'Trash receptacles emptied and relined'),
    ('Line / Pass', 'Pass counter sanitized & heat lamps wiped down'),
    ('Line / Pass', 'Refrigerated line drawers cleaned and restocked'),
    ('Line / Pass', 'Cutting boards scrubbed and flipped');

-- Run this to create the AI reference images table
CREATE TABLE IF NOT EXISTS ai_references (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_key TEXT NOT NULL UNIQUE, -- Format: "Station - Task"
    photo_data TEXT NOT NULL,      -- Base64 encoded reference image
    strictness INTEGER DEFAULT 5   -- 1 to 10 scale
);

-- Note: To allow the Streamlit app to read this data, run:
-- ALTER TABLE ai_references ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Enable read access for all users" ON ai_references FOR SELECT USING (true);
