import re

with open('supabase_schema.sql', 'r') as f:
    content = f.read()

# We need to alter the creation of station_tasks
new_table_def = """CREATE TABLE IF NOT EXISTS station_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station TEXT NOT NULL,
    task TEXT NOT NULL,
    day_of_week TEXT,
    details TEXT
);"""

content = re.sub(r'CREATE TABLE IF NOT EXISTS station_tasks \([^;]+\);', new_table_def, content)

# Remove the old INSERT INTO station_tasks...
content = re.sub(r'-- Insert default tasks\nINSERT INTO station_tasks \(station, task\) VALUES\n(.*?);\n', '', content, flags=re.DOTALL)

with open('supabase_schema.sql', 'w') as f:
    f.write(content)
